security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
    
    providers:
        Admin:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        BackOffice:
            pattern: ^/
            provider: Admin
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: /

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }