languages:
  - es
    titulo: Detecta movimientos con una webcam y Motion en Raspberry Pi
    description: Con Motion podrás detectar movimientos utilizando una webcam en tu Raspberry Pi.
    authors:
      - migueabellan
