version: '3'
 
services:

  mysql:
    build: .docker/mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=bbdd
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    working_dir: /www
    volumes:
      - ./:/www
    ports:
      - 80:80

  phpfpm:
    build: .docker/phpfpm
    container_name: phpfpm
    restart: always
    working_dir: /www
    volumes:
      - ./:/www
